// ─── Excel Error Data ────────────────────────────────────────
// Add new errors here — the page auto-renders them.

const ERRORS = [
  {
    code: '#DIV/0!',
    title: 'Division by Zero',
    meaning: 'Excel is trying to divide a number by zero, or by an empty cell.',
    causes: [
      'A formula divides by a cell that is empty or contains 0',
      '=A1/B1 where B1 is 0 or blank',
      'AVERAGE on an empty range',
    ],
    fixes: [
      'Wrap with IFERROR to show a fallback: =IFERROR(A1/B1, 0)',
      'Use IF to check the divisor first: =IF(B1=0, "N/A", A1/B1)',
      'Ensure the denominator cell is not empty before dividing',
    ],
    fix_formula: '=IFERROR(A1/B1, "—")',
    color: 'red',
  },
  {
    code: '#N/A',
    title: 'Value Not Available',
    meaning: 'A lookup formula cannot find what it\'s looking for. Most common with VLOOKUP, MATCH, XLOOKUP.',
    causes: [
      'The lookup value doesn\'t exist in the lookup range',
      'Extra spaces or different capitalization in data',
      'Lookup value is stored as text but range has numbers (or vice versa)',
      'Using approximate match when exact match is needed',
    ],
    fixes: [
      'Use IFERROR to catch and show a friendly message',
      'Use IFNA specifically for #N/A errors',
      'Trim data: =VLOOKUP(TRIM(A1), D:E, 2, FALSE)',
      'Ensure data types match (both text or both numbers)',
    ],
    fix_formula: '=IFERROR(VLOOKUP(A1, D:E, 2, FALSE), "Not Found")',
    color: 'red',
  },
  {
    code: '#VALUE!',
    title: 'Wrong Value Type',
    meaning: 'A formula or function has the wrong type of argument — e.g., it expects a number but receives text.',
    causes: [
      'Adding a number cell to a text cell: =A1+B1 where B1 is "Hello"',
      'Providing text where a date or number is expected',
      'Spaces in cells that look empty but aren\'t',
      'Date formatted as text cannot be used in date math',
    ],
    fixes: [
      'Check that all cells in the formula contain the right data type',
      'Use VALUE() to convert text-numbers to real numbers',
      'Use TRIM() and CLEAN() to remove invisible characters',
      'Verify cells with ISNUMBER() or ISTEXT()',
    ],
    fix_formula: '=IFERROR(A1+VALUE(B1), "Type mismatch")',
    color: 'red',
  },
  {
    code: '#REF!',
    title: 'Invalid Cell Reference',
    meaning: 'A cell reference is no longer valid — usually because the referenced cell was deleted.',
    causes: [
      'Deleting a row or column that a formula was pointing to',
      'Cutting and pasting cells that are referenced',
      'VLOOKUP col_index is larger than the table width',
      'OFFSET going outside the worksheet boundary',
    ],
    fixes: [
      'Press Ctrl+Z (⌘+Z on Mac) to undo the deletion immediately',
      'Rewrite the formula to point to the correct new location',
      'Use named ranges so references survive moves',
      'Check VLOOKUP column index — can\'t exceed number of columns in table',
    ],
    fix_formula: '=IFERROR(VLOOKUP(A1, D:F, 2, FALSE), "#REF — check column index")',
    color: 'orange',
  },
  {
    code: '#NAME?',
    title: 'Unrecognized Name',
    meaning: 'Excel doesn\'t recognize a name in your formula — usually a typo in a function name or a missing quote.',
    causes: [
      'Typo in a function name: =SUIM() instead of =SUM()',
      'Text value not enclosed in quotes: =IF(A1=Yes, ...) — "Yes" needs quotes',
      'Named range was deleted or misspelled',
      'Using a newer function (XLOOKUP, FILTER) in an older version of Excel',
    ],
    fixes: [
      'Check the formula for typos — Excel will suggest functions as you type',
      'Wrap text values in double quotes: =IF(A1="Yes", ...)',
      'Go to Formulas > Name Manager to check named ranges',
      'Make sure you\'re using a compatible Excel version for newer functions',
    ],
    fix_formula: '=IFERROR(XLOOKUP(A1, D:D, E:E), "Check Excel version")',
    color: 'orange',
  },
  {
    code: '#NUM!',
    title: 'Invalid Numeric Value',
    meaning: 'A formula produces a number that\'s too large, too small, or mathematically impossible.',
    causes: [
      'Square root of a negative number: =SQRT(-1)',
      'Result is too large for Excel to display (> 9.99×10^307)',
      'IRR or RATE can\'t find a valid solution',
      'Negative number raised to a fractional power',
    ],
    fixes: [
      'Check the formula logic for impossible calculations',
      'Use ABS() to ensure non-negative inputs: =SQRT(ABS(A1))',
      'For IRR/RATE, provide a better initial guess',
      'Validate input data before performing calculations',
    ],
    fix_formula: '=IFERROR(SQRT(ABS(A1)), "Invalid input")',
    color: 'orange',
  },
  {
    code: '#NULL!',
    title: 'Invalid Range Intersection',
    meaning: 'You used a space (the intersection operator) between two ranges that don\'t intersect.',
    causes: [
      'Using a space between two ranges that share no cells',
      'Typing =SUM(A1:A10 C1:C10) instead of =SUM(A1:A10, C1:C10)',
      'Accidental space when meant to use a comma or colon',
    ],
    fixes: [
      'Replace the space with a comma to union ranges: =SUM(A1:A10, C1:C10)',
      'Or use a colon for a continuous range: =SUM(A1:C10)',
      'Review the formula bar carefully for accidental spaces',
    ],
    fix_formula: '=SUM(A1:A10, C1:C10)  ← use comma, not space',
    color: 'orange',
  },
  {
    code: '#SPILL!',
    title: 'Spill Range Blocked',
    meaning: 'A dynamic array formula (like FILTER, SORT, UNIQUE) can\'t spill its results because cells in the spill range are occupied.',
    causes: [
      'Data or text exists in cells where the formula wants to spill results',
      'The spill range overlaps with another table or data',
      'A merged cell is blocking the spill area',
    ],
    fixes: [
      'Clear all cells in the spill range (usually highlighted in blue dashes)',
      'Move the blocking data to another location',
      'Unmerge any cells in the expected spill area',
      'Click the error icon to see which cells are blocking',
    ],
    fix_formula: '=IFERROR(FILTER(A:B, C:C>100), "No results")',
    color: 'blue',
  },
  {
    code: '#CALC!',
    title: 'Calculation Error',
    meaning: 'A dynamic array function failed during calculation. Often means the formula returned an empty array.',
    causes: [
      'FILTER() found no matching results and no fallback was provided',
      'An array operation produced no values',
      'Using unsupported operations in array context',
    ],
    fixes: [
      'Add an if_empty argument to FILTER: =FILTER(A:B, C:C>0, "No results")',
      'Use IFERROR to catch and display a friendly message',
      'Verify your filter conditions aren\'t too restrictive',
    ],
    fix_formula: '=FILTER(A1:B20, C1:C20>0, "No matches found")',
    color: 'blue',
  },
  {
    code: '#GETTING_DATA',
    title: 'Waiting for Data',
    meaning: 'Excel is retrieving data from an external source. This is usually temporary — not a true error.',
    causes: [
      'Linked workbooks or external data connections are loading',
      'Stock or currency data types are being fetched',
      'Power Query or data model is still processing',
    ],
    fixes: [
      'Wait a moment — the value usually populates automatically',
      'If persistent, check your internet connection',
      'Manually refresh the data connection: Data > Refresh All',
      'Check if the external data source is available',
    ],
    fix_formula: '=IFERROR(A1, "Data loading...")',
    color: 'blue',
  },
];
