// ─── How-To Guides Hub Data ──────────────────────────────────
// Add new guides here — the hub page auto-renders them.
const GUIDES = [
  {
    emoji: '📊',
    title: 'PivotTables',
    difficulty: 'intermediate',
    minutes: 8,
    description: 'Summarize thousands of rows in seconds. Learn to create, group, filter, and refresh PivotTables.',
    url: 'guides/pivot-tables.html',
  },
  {
    emoji: '🎨',
    title: 'Conditional Formatting',
    difficulty: 'beginner',
    minutes: 5,
    description: 'Highlight cells automatically with color rules, data bars, color scales, and icon sets.',
    url: 'guides/conditional-formatting.html',
  },
  {
    emoji: '🔍',
    title: 'VLOOKUP vs XLOOKUP',
    difficulty: 'beginner',
    minutes: 6,
    description: 'Master the most-used lookup formulas. Step-by-step examples and when to use each.',
    url: 'guides/vlookup-vs-xlookup.html',
  },
  {
    emoji: '✅',
    title: 'Data Validation & Drop-downs',
    difficulty: 'beginner',
    minutes: 5,
    description: 'Create drop-down lists, restrict input types, and show custom error messages.',
    url: 'guides/data-validation.html',
  },
  {
    emoji: '📈',
    title: 'Charts & Graphs',
    difficulty: 'beginner',
    minutes: 6,
    description: 'Create professional charts, choose the right type for your data, and format like a pro.',
    url: 'guides/charts.html',
  },
  {
    emoji: '🔄',
    title: 'Power Query',
    difficulty: 'advanced',
    minutes: 10,
    description: 'Import, clean, and transform data from any source — without writing formulas.',
    url: 'guides/power-query.html',
  },
  {
    emoji: '🏷️',
    title: 'Named Ranges',
    difficulty: 'intermediate',
    minutes: 5,
    description: 'Name your ranges to make formulas readable, maintainable, and less error-prone.',
    url: 'guides/named-ranges.html',
  },
  {
    emoji: '🎯',
    title: 'What-If Analysis',
    difficulty: 'advanced',
    minutes: 8,
    description: 'Use Goal Seek, Data Tables, and Scenario Manager to model outcomes and "what if" scenarios.',
    url: 'guides/what-if-analysis.html',
  },
  {
    emoji: '🔒',
    title: 'Protecting Sheets & Workbooks',
    difficulty: 'beginner',
    minutes: 4,
    description: 'Lock cells, protect sheets with passwords, and control what others can edit.',
    url: 'guides/protect-sheets.html',
  },
  {
    emoji: '⚡',
    title: 'Dynamic Arrays',
    difficulty: 'intermediate',
    minutes: 7,
    description: 'Use FILTER, SORT, UNIQUE, and SEQUENCE to build formulas that return entire ranges automatically.',
    url: 'guides/dynamic-arrays.html',
  },
  {
    emoji: '🤖',
    title: 'Macros & Basic VBA',
    difficulty: 'advanced',
    minutes: 10,
    description: 'Record and run macros to automate repetitive tasks. Intro to the VBA editor.',
    url: 'guides/macros.html',
  },
  {
    emoji: '🧮',
    title: 'Solver',
    difficulty: 'advanced',
    minutes: 8,
    description: 'Use Excel\'s Solver add-in to find optimal solutions with constraints — great for scheduling and resource allocation.',
    url: 'guides/solver.html',
  },
];
